app/models.py
from app.modules import db


class Clients(db.Model):
    id = db.Column('id', db.Integer, primary_key=True)
    name = db.Column(db.String(200))
    email = db.Column(db.String(200))
    referral_email = db.Column(db.String(200))
    points = db.Column(db.Integer, default=0)

    def __init__(self, name, email, referral_email, points):
        self.name = name
        self.email = email
        self.referral_email = referral_email
        self.points = points

app/__init__.py
from flask import Flask
import os


def create_app(debug=None) -> Flask:
    # Initialize app
    app = Flask(
        __name__,
        template_folder='../templates',
        static_folder='../static',
        static_url_path='/assets/'
        )
    app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DB')
    app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')


    # # Initialize extensions
    from app.modules import db
    db.init_app(app)
    # csrf.init_app(app)
    # bcrypt.init_app(app)
    # login_manager.init_app(app)

    # Create database tables
    from app import models
    with app.app_context():
        db.create_all()

    # Register blueprints
    from app.routes import routes_bp
    app.register_blueprint(routes_bp)

    return app

app/routes.py
# Flask modules
from flask import Blueprint, request, redirect, url_for, render_template, flash

# Local modules
from app.models import Clients
from app.modules import db
from app.solutions import s1, s2

routes_bp = Blueprint('routes', __name__, url_prefix="/")


@routes_bp.route('/')
def show_all():
    return render_template('index.html', clients=Clients.query.all())


@routes_bp.route('/crud')
def crud():
    return render_template('crud.html', clients=Clients.query.all())

@routes_bp.route('/q1', methods=['GET', 'POST'])
def question_1():
    if request.method == 'POST':
        input = request.form['email']
        output = s1(input)
        if output != {}:
            flash(f'Showing Referall tree for {input}', 'success')
        else:
            flash(f'Email not found in the database', 'danger')
        return render_template('question_1.html' , output=output)
    return render_template('question_1.html')

@routes_bp.route('/q2', methods=['GET', 'POST'])
def question_2():
    if request.method == 'POST':
        print('post')
        input = request.form['email']
        client = s2(input)
        if client is None:
            flash(f'Email not found in the database', 'danger')
        else:
            flash(f'Showing details for {input}', 'success')
        return render_template('question_2.html', client=client)
    return render_template('question_2.html')

@routes_bp.route('/q3_6')
def question_36():
    return render_template('question_36.html')


@routes_bp.route('/new', methods=['GET', 'POST'])
def new():
    if request.method == 'POST':
        if not request.form['name'] or\
           not request.form['email']:
            flash('Please enter all the fields', 'error')
        else:
            client = Clients(
               request.form['name'],
               request.form['email'],
               request.form['referral_email'],
               request.form['points']
            )
            db.session.add(client)
            db.session.commit()
            flash('Record was successfully added')
            return redirect(url_for('routes.crud'))
    return render_template('new.html')

@routes_bp.route('/update/<int:client_id>', methods=['GET', 'POST'])
def update(client_id):
    if request.method == 'POST':
        client=Clients.query.get(client_id)
        client.name =request.form['name']
        client.email =request.form['email']
        client.referral_email =request.form['referral_email']
        client.points =request.form['points']
        db.session.commit()
        flash('Record was successfully updated')
        return redirect(url_for('routes.crud'))

    return render_template('update.html', client=Clients.query.get(client_id))

@routes_bp.route('/delete', methods=['POST'])
def delete():
    if request.method == 'POST':
        client_id = request.form['delete']
        print(client_id)
        client=Clients.query.get(client_id)
        db.session.delete(client)
        db.session.commit()
        flash('Record was successfully deleted')
        return redirect(url_for('routes.crud'))


main.py
from app import create_app
import os
from dotenv import load_dotenv


if __name__ == '__main__':
    load_dotenv(override=True)
    debug = os.getenv('DEBUG') == 'True'
    app = create_app()
    app.run(debug=debug)

templates/crud.html

{% extends "master.html" %}
{% block title %}Database{% endblock %}
{% block head %}
  {{ super() }}

{% endblock %}
{% block content %}
<div class="px-3 pt-2">
<h3>
   Database Simple CRUD</a>
</h3>

<hr>
{%- for message in get_flashed_messages() %}
<div class="alert alert-warning alert-dismissible fade show " role="alert">
   <strong class="mb-0">{{ message }}</strong>
   <button type="button" class="btn-close btn-sm" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{%- endfor %}
<div class="d-flex">
<h3>Clients </h3>
<a class="btn btn-lg p-0 text-primary" href="{{ url_for('routes.new') }}" title="Add Client">
   <i class="bi bi-plus-lg"></i>
</a>
</div>
<hr>
<div class="overflow-scroll">
<table class="table ">
   <thead>
      <tr class="table-dark">
         <th>Name</th>
         <th>Email</th>
         <th>Referral Email</th>
         <th>Points</th>
         <th class="text-center">Actions</th>
      </tr>
   </thead>

   <tbody>
      {% for client in clients %}
         <tr>
            <td>{{ client.name }}</td>
            <td>{{ client.email }}</td>
            <td>{{ client.referral_email }}</td>
            <td>{{ client.points }}</td>
            <td >
               <div class="d-flex justify-content-evenly">
               <button class="btn btn-sm d-inline text-success" href="{{ url_for('routes.update', client_id=client.id) }}" title="Edit">
                  <i class="bi bi-pencil"></i></button>
               |
               <form id="delete_{{client.id}}" action="{{url_for('routes.delete')}}" method="post">
                  <input type="hidden" name="delete" value="{{client.id}}">
               <button class="btn btn-sm d-inline text-danger" href="#" title="Delete" onClick="confirmDelete({{client.id}})">
                  <i class="bi bi-trash"></i>
               </button>
               </form>
            </div>
            </td>
         </tr>
      {% endfor %}
   </tbody>
</table>
</div>
</div>
<script>
   function confirmDelete(client_id) {
      var txt;
      if (confirm("Are you sure you want to delete this client?")) {
         document.getElementById("delete_" + client_id).submit()
      } else {
        event.preventDefault();
      }
    }
</script>
{% endblock %}

templates/header.html
<link rel="stylesheet"  href="{{ url_for('static', filename = 'css/navbar.css') }}">
<link rel="icon" type="image/x-icon" href="{{ url_for('static', filename = 'img/favicon.ico') }}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

templates/index.html
{% extends "master.html" %}
{% block title %}Home Page{% endblock %}
{% block head %}
  {{ super() }}
  <link rel="stylesheet"  href="{{ url_for('static', filename = 'css/home.css') }}">

{% endblock %}
{% block content %}
<div id="container">
    <h1 class="ps-2">AlphaMasterclass Technical Interview (Flask App)</h1>
    <hr class="mb-2">
  <div id="home_main">
    <a href = "{{ url_for('routes.crud') }}">
    <div class="home_sub">
        <h2>Database</h2>
        <div class="sub_main">
        <div></div>
        <h3>Optional Database CRUD using SQLite</h3>
            <div></div>
        </div>
    </div>
    </a>
    <a href = "{{ url_for('routes.question_1') }}">
    <div class="home_sub">
        <h2>Question1</h2>
        <div class="sub_main">
        <div></div>
            <h3>Q1</h3>
            <div></div>
        </div>
    </div>
    </a>
    <a href = "{{ url_for('routes.question_2') }}">
    <div class="home_sub">
        <h2>Question 2</h2>
        <div class="sub_main">
        <div></div>
            <h3>Q2</h3>
            <div></div>
        </div>
    </div>
    </a>    
    <a href = "{{ url_for('routes.question_36') }}">
    <div class="home_sub">
        <h2>Question 3-6</h2>
        <div class="sub_main">
        <div></div>
            <h3>Q 3-6</h3>
            <div></div>
        </div>
    </div>
    </a>
 
  </div>
  </div>
{% endblock %}

templates/master.html
<!DOCTYPE html>
<html>
  <head>
    {% block head %}
    <title>{% block title %}{% endblock %}</title>
    {% include "header.html" %}
    {% endblock %}
  </head>
  <body>
    {% include "navbar.html" %}
    {% block content %}
    {% endblock %}

    {% block footer %}
      
    {% endblock %}
  </body>
</html>

templates/navbar.html
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/"><img src="{{ url_for('static', filename = 'img/icon.png') }}" alt="" width="30" height="24"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
        <li class="nav-item mx-2">
            <a class="nav-link" href="{{ url_for('routes.crud') }}" role="button" aria-expanded="false">
            DB
            </a>
        </li>
        <li class="nav-item mx-2">
            <a class="nav-link" href="{{ url_for('routes.question_1') }}" role="button" aria-expanded="false">
            Q1
            </a>
        </li>
        <li class="nav-item mx-2">
            <a class="nav-link" href="{{ url_for('routes.question_2') }}" role="button" aria-expanded="false">
            Q2
            </a>
        </li>
        <li class="nav-item mx-2">
            <a class="nav-link" href="{{ url_for('routes.question_36') }}" role="button" aria-expanded="false">
            Q 3 - 6
            </a>
        </li>
        </ul>
    </div>
    </div>
</nav>

templates/new.html
{% extends "master.html" %}
{% block title %}Add Client{% endblock %}
{% block head %}
  {{ super() }}

{% endblock %}
{% block content %}
<h3>Clients</h3>
<hr/>

{%- for category, message in get_flashed_messages(with_categories = true) %}
   <div class = "alert alert-danger">
      {{ message }}
   </div>
{%- endfor %}

<form action = "{{ request.path }}" method = "post">
   <label for = "name">Name</label><br>
   <input type = "text" name = "name" placeholder = "Name" /><br>
   <label for = "email">Email</label><br>
   <input type = "email" name = "email" placeholder = "Email" /><br>
   <label for = "referral_email">Referral Email</label><br>
   <input type = "email" name = "referral_email" placeholder = "Referral Email" /><br>
   <label for = "points">Points</label><br>
   <input type = "number" name = "points" placeholder = "points" /><br>
   <input type = "submit" value = "Submit" />
</form>
{% endblock %}
      

templates/question_1.html
{% extends "master.html" %}
{% block title %}Question 1{% endblock %}
{% block head %}
  {{ super() }}

{% endblock %}
{% block content %}
<div class="px-3">
    <h1>Question 1</h1>
    <p>Our clients can refer their friends to join any of our events. They would share their email to identify the referral relationship. </p>
    <hr>
    <h2>Task:</h2> 
    <p>
        Use Flask to display the referral relationship for all clients under the main referrer. 
        <br>Implement a basic UI that is user friendly. 
        <br>Optional: Implementing a <a href = "{{ url_for('routes.crud') }}">database</a>.</p>
    <br>
    <p>A mock data set is provided in <a href="{{ url_for('static', filename = 'doc/client.csv') }}">client.csv</a></p>
    <hr>
    <h2>Solution</h2>
    <form id="q1_input" action="#" method="post">
        <input type="email" placeholder="Email" name="email"><input type="submit" value="Submit">
    </form>
    {%- for category, message in get_flashed_messages(with_categories = true) %}
    <div class="alert alert-{{category}} alert-dismissible fade show " role="alert">
    <strong class="mb-0">{{ message }}</strong>
    <button type="button" class="btn-close btn-sm" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {%- endfor %}
    {%- if output -%}
    <div class="mt-2">
        <ul>
        {%- for key, value in output.items() recursive %}
        {%- set indent = loop.depth * 2 %}  {# Adjust the multiplier (4 spaces) based on your preferred indentation level #}
        <li style="margin-left: {{ indent }}ex;">{{ key }}</li>
            {%- if value is mapping -%}
                {{ loop(value.items()) }}
            {%- endif -%}
        {%- endfor %}
        </ul>
    </div>
    {%- endif -%}
</div>
{% endblock %}

templates/question_2.html
{% extends "master.html" %}
{% block title %}Question 2{% endblock %}
{% block head %}
  {{ super() }}

{% endblock %}
{% block content %}
<div class="px-3">
    <h1>Question 2</h1>
    <hr>
    <h2>Task:</h2> 
    <p>
      Build a simple API on Flask that accepts a POST request given an email address. 
      <br>Then, create a basic web page that uses JavaScript to create a POST request to retrieve the name and points given an email.
    </p>
    <h2>Solution</h2>
    <form action="#" method="post">
      <input type="email" placeholder="Email" name="email"><input type="submit" value="Submit">
    </form>
    {%- for category, message in get_flashed_messages(with_categories = true) %}
    <div class="alert alert-{{category}} alert-dismissible fade show " role="alert">
    <strong class="mb-0">{{ message }}</strong>
    <button type="button" class="btn-close btn-sm" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {%- endfor %}
    {%- if client -%}
    <div>
        <table class="table mt-3">
          <thead>
            <tr class="table-dark">
              <th>Email</th>
              <th>Name</th>
              <th>Points</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{client.email}}</td>
              <td>{{client.name}}</td>
              <td>{{client.points}}</td>
            </tr>
          </tbody>
        </table>
    </div>
    {%- endif -%}
</div>
{% endblock %}

templates/question_36.html
{% extends "master.html" %}
{% block title %}Question 3 to 6{% endblock %}
{% block head %}
  {{ super() }}

{% endblock %}
{% block content %}
<div class="px-3 mt-3">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="q3-tab" data-bs-toggle="tab" data-bs-target="#q3" type="button" role="tab" aria-controls="q3" aria-selected="true"><h3>Question 3</h3></button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="q4-tab" data-bs-toggle="tab" data-bs-target="#q4" type="button" role="tab" aria-controls="q4" aria-selected="false"><h3>Question 4</h3></button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="q5-tab" data-bs-toggle="tab" data-bs-target="#q5" type="button" role="tab" aria-controls="q5" aria-selected="false"><h3>Question 5</h3></button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="q6-tab" data-bs-toggle="tab" data-bs-target="#q6" type="button" role="tab" aria-controls="q6" aria-selected="false"><h3>Question 6</h3></button>
    </li>
  </ul>
  <div class="tab-content mt-1" id="myTabContent">
    <div class="tab-pane fade show active" id="q3" role="tabpanel" aria-labelledby="q3-tab">
      <h4>Scenario</h4>
      <p>Our admin team would like to collect information about our client's subscription habits for business decision making.</p>
      <h4>Task</h4>
      <p>Share with us how would you implement the scenario - (you are free be as creative as you wish but robustness, practicality and simplicity would suffice)</p>
      <h4>Questions of interests:</h4>
      <ul>
        <li>What would you implement? (Assuming a database and CRM of all the clients already exists)</li>
        <li>How would you implement? (Tech-stacks used, any special features, computation algorithms etc.)</li>
        <li>What kind of value would the admin team be able to get? (Hint: Tracking information is always useful)</li>
      </ul>
      <hr>
      <h3>Answer</h3>
      <ul>
        <li>
          We can already gather a lot of information by utilizing existing tools such as Google Analytics. This provides a variety of data including:
          <ul>
            <li>Traffic sources</li>
            <li>Page hits</li>
            <li>Path exploration</li>
            <li>Browser information</li>
            <li>Country of origin</li>
          </ul>
          These insights can be used in conjunction with our client database to better profile and map our target markets. Additionally, analyzing:
          <ul>
            <li>Page hits</li>
            <li>Path explorations</li>
          </ul>
          allows us to monitor which features are being used most frequently or are enticing clients to subscribe. This information helps us understand what to prioritize for prospective clients and provides suggestions for improvements or upgrades.
        </li>
        <br>
        <li>
          From our existing database, we can generate reports to monitor subscription habits. This involves adding attributes such as:
          <ul>
            <li>Date of subscription/cancellation</li>
            <li>Renewal counts</li>
            <li>Whether a discount/promotion/bundle was considered</li>
          </ul>
          To achieve this, we ensure our database is properly time-stamped and tracks as many attributes as possible. Such functionality is available in various frameworks like Laravel or Django, either natively or through plugins.
        </li>
        <br>
        <li>
          Adding audits to our platform enhances our ability to monitor user activity in greater detail. Audits allow us to track user actions as they navigate the system, including:
          <ul>
            <li>Updating their information</li>
            <li>Login times</li>
            <li>Pages/modules accessed</li>
          </ul>
          This functionality can be incorporated using plugins available in frameworks such as Django or Laravel.
          <br>
        </li>
      </ul>
      
    </div>
    <div class="tab-pane fade" id="q4" role="tabpanel" aria-labelledby="q4-tab">
      <h4>Scenario</h4>
      <p>We have several marketing platforms for marketing and sales. Each platform has their own version of storing client’s data.</p>
      <h4>Task</h4>
      <p>Suggest a plausible solution that would be best to store the data for use in the future and methods for data cleaning.</p>
      <hr>
      <h3>Answer</h3>
      <ul>
        <li>Ideally the we have a separate centralized database server for the platforms to connect to.</li>
        <li>While each platfomr might have different ways of storing clients data as in different attributes or differing values depending on the platform the client data can still using a <b>Master Table</b> that is reffrenced by each platform.</li>
        <li>This will allow each platform to be customizable while still have only a single master table for the client information to ensure data consistency.</li>
        <li>We can clean the data by identifying the the essential values of the client(ID, names or any universally used values) and use that as the master table which then the separate platform can assign attributes and values specific to them</li>
        <li>This way we can avoid data duplication and make sure data consistency between platform and simplifies maintenance and updates by only having 1 source.</li>
      </ul>
    </div>
    <div class="tab-pane fade" id="q5" role="tabpanel" aria-labelledby="q5-tab">
      <h4>Scenario</h4>
      <p>A free finance news API allows 10 calls per minute. Each API call would take in a financial keyword (ie. inflation) and would take 5 seconds to process its sentiment analysis to be sent to the end-user. As the number of end-users increases, the frequency of calls increases greatly.</p>
      <h4>Task</h4>
      <p>Suggest one or more implementations that would allow the end-user to still receive the requested info with lesser disturbances or delay.</p>
      <hr>
      <h3>Answer</h3>
      <ul>
        <li>Best method is using caching to increase responsiveness and reduce the resources used by the system by having the data stored somewhere and can be retrieved immediately instead of doing the process over and over again.</li>
        <li>Some frameworks like Django have server side caching which you can configure to use whatever method is most suitable (memory, file, database(regular or redis)) depending on the scale and usage of the application.</li>
        <li>In this case when a user or another user try to request another keyword that have been requested before, instead of taking 5 seconds to do the process, it can just send the data to the uses.</li>
        <li>One thing to keep in mind is on the source data volatilty. Caching might not the best solution to highly volatile data since it will cause the data to be stale. One way to circumvent this(depending on the nature of the api) is to have a list of popular keyword and have trigger to prefecth the data for them when something in the backend is updated.</li>
      </ul>
    </div>
    <div class="tab-pane fade" id="q6" role="tabpanel" aria-labelledby="q6-tab">
      <h4>Scenario</h4>
      <p>As the project leader of an AI chat bot, your team informs you that the number of active users is reducing and the average use time of the users are decreasing.</p>
      <h4>Task</h4>
      <p>Suggest any features that can be added into the chat bot that would increase its subscription value (economic value or user experience). Try to maximize value while minimizing the cost (economic cost, computational cost).</p>
      <hr>
      <h3>Answer</h3>
      Some of my suggestions would be:
      <ul>
        <li>Interactiveness: adding interaction like games or quizzes</li>
        <li>Multi-modal Support: add support for images, video and audio</li>
        <li>Third Party Intergration: add functionalities to use other app/services through the chatbot like ordering a ride from grab, or buying an item through shopee, etc.</li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

templates/template.html
{% extends "master.html" %}
{% block title %}Index{% endblock %}
{% block head %}
  {{ super() }}

{% endblock %}
{% block content %}

{% endblock %}

templates/update.html
{% extends "master.html" %}
{% block title %}Update Client{% endblock %}
{% block head %}
  {{ super() }}

{% endblock %}
{% block content %}
<h3>Clients</h3>
<hr/>

{%- for category, message in get_flashed_messages(with_categories = true) %}
   <div class = "alert alert-danger">
      {{ message }}
   </div>
{%- endfor %}

<form action = "{{ request.path }}" method = "post">
   <label for = "name">Name</label><br>
   <input type = "text" name = "name" placeholder = "Name" value="{{ client.name}}"/><br>
   <label for = "email">Email</label><br>
   <input type = "email" name = "email" placeholder = "Email" value="{{ client.email}}"/><br>
   <label for = "referral_email">Referral Email</label><br>
   <input type = "email" name = "referral_email" placeholder = "Referral Email" value="{{ client.referral_email}}"/><br>
   <label for = "points">Points</label><br>
   <input type = "number" name = "points" placeholder = "points" value="{{ client.points}}"/><br>
   <input type = "submit" value = "Submit" />
</form>
{% endblock %}
      